### ISSUE TITLE
Create beagleboard sdcard image

### ISSUE THREAD

**Issue by m-1-k-3** [eurecom-s3/avatar-samples#2]
Hey guys,

 in your beagleboard sample a compiled u-boot version is included. 
In your script you use multiple u-boot files that are not included in your images directory:

```
sudo cp ${UBOOT_DIR}/MLO ${UBOOT_DIR}/u-boot.img ${UBOOT_DIR}/u-boot.bin ${tmp_dir}
```

 What are the correct steps to create the needed sdcard image from the u-boot file that is included in the sample?

 Best,
 Mike

**Comment by cojocar** [comment]
Hi @m-1-k-3,

AFAIK the u-boot related files (`MLO`,`u-boot.img`, `u-boot.bin`) were created following the instructions from [here](http://elinux.org/Panda_How_to_MLO_%26_u-boot). IIRC, the latest version of u-boot does not use the `MLO` (minimal bootloader) anymore. _Probably_ it will work with just `u-boot.bin` inside that image file.

Anyway, I'm attaching an archive with the three files that we used for testing (I don't know if they are suppose to work or not as I was hacking u-boot when I generated them).

[sdimage.zip](https://github.com/eurecom-s3/avatar-samples/files/309463/sdimage.zip)

The other parts of the script should work as intended.

Thanks,
Lucian
